annotations:
  artifacthub.io/cr.source: gotify/server
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/images: "- name: gotify\n  image: gotify/server:2.6.3\n  platforms:\n\
    \    - linux/amd64\n"
  artifacthub.io/license: MIT
  artifacthub.io/links: "- name: Source\n  url: https://github.com/pmoscode-helm/gotify\n\
    - name: support\n  url: https://github.com/pmoscode-helm/gotify/issues\n"
  artifacthub.io/maintainers: "- name: pmoscode\n  email: info@pmoscode.de\n"
  artifacthub.io/own.source: gotify_server
apiVersion: v2
appVersion: 2.9.0
description: Gotify - a simple server for sending and receiving messages
home: https://gotify.net/
icon: https://github.com/gotify/logo/raw/master/gotify-logo-small.png
maintainers:
- email: info@pmoscode.de
  name: pmoscode
  url: https://pmoscode.de
name: gotify
sources:
- https://gotify.net/
type: application
version: 0.5.2
