apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 18789
      protocol: TCP
  selector:
    {{- include "openclaw.selectorLabels" . | nindent 4 }}
