annotations:
  artifacthub.io/cr.source: langflowai/langflow-frontend
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: langflow-frontend
apiVersion: v2
appVersion: 1.7.2
description: A Helm chart for Langflow
name: langflow
type: application
version: 0.1.0
