annotations:
  artifacthub.io/cr.source: mintplexlabs/anythingllm
  artifacthub.io/cr.update-strategy: github
  artifacthub.io/github.source: https://api.github.com/repos/Mintplex-Labs/anything-llm/releases/latest
  artifacthub.io/own.source: anythingllm
apiVersion: v2
appVersion: 1.11.0
description: A Helm chart for AnythingLLM
name: anythingllm
type: application
version: 0.1.0
