annotations:
  artifacthub.io/cr.source: shaarli/shaarli
  artifacthub.io/cr.update-strategy: github
  artifacthub.io/github.source: https://api.github.com/repos/shaarli/shaarli/releases/latest
  artifacthub.io/own.source: shaarli
apiVersion: v2
appVersion: 0.16.1
description: A Helm chart for shaarli - The personal, minimalist, super-fast, database
  free, bookmarking service
name: shaarli
type: application
version: 0.1.0
