annotations:
  artifacthub.io/cr.source: amruthpillai/reactive-resume
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: reactive-resume
apiVersion: v2
appVersion: v5.0.5
description: A Helm chart for Reactive Resume
name: reactive-resume
type: application
version: 0.1.0
