annotations:
  artifacthub.io/cr.source: ghcr.io/codex-team/codex.docs
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: codex.docs
apiVersion: v2
appVersion: v2.2.4
description: A Helm chart for CodeX Docs
name: codex-docs
type: application
version: 2.1.2
