apiVersion: v1
kind: Secret
metadata:
  name: {{ include "copaw.fullname" . }}-env
  labels:
    {{- include "copaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  DASHSCOPE_API_KEY: {{ .Values.externalEnv.DASHSCOPE_API_KEY | quote }}
