annotations:
  artifacthub.io/cr.source: etherpad/etherpad
  artifacthub.io/cr.update-strategy: latest
  artifacthub.io/own.source: etherpad
apiVersion: v2
appVersion: 2.6.1
description: A Helm chart for Etherpad Lite - a real-time collaborative editor
home: https://etherpad.org
keywords:
- etherpad
- collaborative
- editor
- realtime
maintainers:
- name: Etherpad Team
name: etherpad
sources:
- https://github.com/ether/etherpad-lite
type: application
version: 1.0.0
