apiVersion: v1
kind: Service
metadata:
  name: {{ include "hiclaw.fullname" . }}
  labels:
    {{- include "hiclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: element-web
      port: {{ .Values.service.elementWebPort }}
      targetPort: element-web
    - name: gateway
      port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: console
  selector:
    {{- include "hiclaw.selectorLabels" . | nindent 4 }}
